# Write your MySQL query statement below
SELECT DISTINCT LOGS1.Num as ConsecutiveNums FROM LOGS LOGS1
INNER JOIN LOGS LOGS2 ON LOGS1.Id + 1 = LOGS2.Id
INNER JOIN LOGS LOGS3 ON LOGS2.Id + 1 = LOGS3.Id
WHERE LOGS1.Num = LOGS2.Num and LOGS2.Num = LOGS3.Num;
